name: Update README Daily

on:
  schedule:
    - cron: '00 0 * * *'  # 每天 8:00 执行一次

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get aphorism
        run: |
          response=$(curl -s https://api.juejin.cn/growth_api/v1/get_coder_calendar)
          # sentence=$(echo "$response" | jq -r '.data.aphorism')
          # echo "$(date +'%Y-%m-%d'): $sentence" >> README.md

          # 查找并提取 aphorism 字段的值
          aphorism=$(echo "$response" | grep -Po '"aphorism": *\K"[^"]*"')

          # 查找并提取 should_or_not 字段的值
          should_or_not=$(echo "$response" | grep -Po '"should_or_not": *\K"[^"]*"')

          # 去除双引号
          aphorism=$(echo "$aphorism" | tr -d '"')
          should_or_not=$(echo "$should_or_not" | tr -d '"')

          echo "| $(date +'%Y-%m-%d') | $should_or_not | $aphorism |" >> aphorism.md

      - name: Commit files
        run: |
          git config --local user.email "zhangsanplus@gmail.com"
          git config --local user.name "zhangsanplus"
          git add aphorism.md
          git commit -m "Update aphorism.md"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          branch: main  # 指定要推送的主分支名称
